# Generated by Django 5.1.1 on 2024-12-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('key', models.CharField(max_length=128, verbose_name='ключ')),
                ('file', models.FileField(upload_to='files', verbose_name='Файл')),
                ('file_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Идентификатор файла')),
            ],
            options={
                'verbose_name': 'Файл в боте',
                'verbose_name_plural': 'Файлы в боте',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('key', models.CharField(max_length=128, verbose_name='ключ')),
                ('photo', models.FileField(upload_to='photos', verbose_name='Фото')),
                ('file_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Идентификатор файла')),
            ],
            options={
                'verbose_name': 'Фото в боте',
                'verbose_name_plural': 'Фото в боте',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('key', models.CharField(max_length=128, verbose_name='ключ')),
                ('key_type', models.CharField(choices=[('IK', 'InlineKB'), ('RK', 'ReplyKB'), ('TXT', 'Text'), ('CAP', 'Caption')], default='TXT', max_length=3, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Ключ',
                'verbose_name_plural': 'Ключи',
            },
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('translate', models.TextField(max_length=4096, verbose_name='Текст')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_text', to='bot_data.language')),
                ('text_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_translates', to='bot_data.text')),
            ],
            options={
                'verbose_name': 'Текст на языке',
                'verbose_name_plural': 'Тексты на языках',
            },
        ),
    ]
