# Generated by Django 5.1.1 on 2025-01-07 11:56

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0005_alter_telegramuser_bot_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('lt_count', models.IntegerField(blank=True, null=True, verbose_name='До скольки строк')),
                ('price', models.IntegerField(default=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цену на таблицу',
                'verbose_name_plural': 'Цены на таблицы',
                'ordering': ['lt_count'],
            },
        ),
        migrations.CreateModel(
            name='BotAddedToPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255)),
                ('place_type', models.CharField(choices=[('group', 'Группа (чат)'), ('supergroup', 'Супергруппа (чат)'), ('channel', 'Канал')], verbose_name='Тип места')),
                ('place_id', models.CharField(max_length=255, unique=True, verbose_name='ID места в которое добавили бота')),
                ('admin_rights', models.BooleanField(default=False)),
                ('channel_username', models.CharField(blank=True, max_length=512, null=True, verbose_name='Юзернейм публичного канала')),
                ('admin_or_owner', models.ManyToManyField(blank=True, related_name='chats', to='telegram.telegramuser', verbose_name='Админ или владелец')),
            ],
            options={
                'verbose_name': 'Куда бот добавлен',
                'verbose_name_plural': 'Места куда бот добавлен',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('unique_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True)),
                ('giv_text', models.TextField(blank=True, null=True, verbose_name='Текст розыгрыша')),
                ('video_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ID видео')),
                ('video', models.FileField(blank=True, null=True, upload_to='giv_videos', verbose_name='Видео')),
                ('photo', models.FileField(blank=True, null=True, upload_to='giv_photos', verbose_name='Фото')),
                ('photo_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ID фото')),
                ('button_type_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='Текст кнопки')),
                ('winners_count', models.IntegerField(default=1, verbose_name='Количество победителей')),
                ('post_giv_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время публикации')),
                ('giv_results_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подведения итогов')),
                ('giv_results_count', models.IntegerField(blank=True, null=True, verbose_name='Итоги по количеству участников')),
                ('ended', models.BooleanField(default=False, verbose_name='Закончен')),
                ('deleted_by_creator', models.BooleanField(default=False, verbose_name='Удален создателем')),
                ('ended_by_creator', models.BooleanField(default=False, verbose_name='Завершен создателем')),
                ('check_sub_channels', models.ManyToManyField(blank=True, related_name='check_sub_givs', to='randomizer.botaddedtoplace', verbose_name='Проверка подписки на эти каналы')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.telegramuser')),
                ('post_channels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='givs', to='randomizer.botaddedtoplace', verbose_name='Где опубликовать розыгрыш')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыши',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayPostMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('message_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='id поста')),
                ('message_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на сообщение')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giv_posts', to='randomizer.botaddedtoplace')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='randomizer.giveaway')),
            ],
            options={
                'verbose_name': 'Сообщение с розыгрышем',
                'verbose_name_plural': 'Сообщения с розыгрышем',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GivParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО из ТГ')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ник Телеграм')),
                ('bot_blocked', models.BooleanField(default=False, verbose_name='Бот заблокирован')),
                ('giveaway', models.ManyToManyField(blank=True, related_name='parts', to='randomizer.giveaway')),
            ],
            options={
                'verbose_name': 'Участник розыгрыша',
                'verbose_name_plural': 'Участники розыгрыша',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayWinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('place', models.IntegerField(verbose_name='Место')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='randomizer.giveaway', verbose_name='Розыгрыш')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='randomizer.givparticipant', verbose_name='Участник розыгрыша')),
            ],
            options={
                'verbose_name': 'Победитель розыгрыша',
                'verbose_name_plural': 'Победители розыгрыша',
                'ordering': ['-created_at'],
                'unique_together': {('place', 'giveaway'), ('winner', 'giveaway')},
            },
        ),
    ]
