# Generated by Django 5.1.1 on 2024-12-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО из ТГ')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ник Телеграм')),
                ('selected_language', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_data.language', verbose_name='Выбранный язык')),
            ],
            options={
                'verbose_name': 'Телеграм Юзер',
                'verbose_name_plural': 'Телеграм Юзеры',
                'ordering': ['-name'],
            },
        ),
    ]
