# Generated by Django 5.1.1 on 2024-12-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
