# Generated by Django 5.1.1 on 2024-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='bot_blocked',
            field=models.BooleanField(default=False, null=True, verbose_name='Бот заблокирован'),
        ),
    ]
