# Generated by Django 5.1.1 on 2024-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegramuser_bot_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='bot_blocked',
            field=models.BooleanField(default=False, verbose_name='Бот заблокирован'),
        ),
    ]
